import {useEffect,useState} from 'react';
type Campaign={id:string;slug:string|null;status:string;data:Record<string,unknown>};
function Calendar(){
 const[items,setItems]=useState<Campaign[]>([]),[error,setError]=useState(''),[month,setMonth]=useState('');
 useEffect(()=>{fetch('/_emdash/api/plugins/globos-promotions/calendar',{credentials:'same-origin',headers:{'X-EmDash-Request':'1'}}).then(async r=>{const b=await r.json() as {error?:{message?:string};data:{items:Campaign[]}};if(!r.ok)throw Error(b.error?.message||'No se pudo cargar el calendario');setItems(b.data.items);}).catch(e=>setError(e.message));},[]);
 const format=(v:unknown)=>{const date=new Date(String(v));return Number.isFinite(date.getTime())?new Intl.DateTimeFormat('es-CO',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Bogota'}).format(date):'Sin definir';};
 return <div className="promotion-calendar"><style>{`.promotion-calendar{padding:24px;max-width:1150px}.promotion-calendar h1{font-size:28px;font-weight:700}.promotion-calendar p{margin:12px 0}.promotion-calendar table{width:100%;border-collapse:collapse;margin-top:24px}.promotion-calendar th,.promotion-calendar td{text-align:left;border-bottom:1px solid #8885;padding:14px;vertical-align:top}.promotion-calendar a{text-decoration:underline}.promotion-calendar input{border:1px solid #8888;border-radius:6px;padding:8px;color:inherit;background:transparent}.promotion-calendar .table-wrap{overflow:auto}.promotion-calendar small{display:block;opacity:.75}`}</style>
 <h1>Calendario de promociones</h1><p>Fechas en hora de Colombia. Un borrador no se muestra en el sitio. Publica una campaña después de confirmar la oferta, los cursos y el cupón.</p>
 <label>Mes <input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label> <button onClick={()=>setMonth('')}>Ver todas</button>
 {error&&<p role="alert">{error}</p>}<div className="table-wrap"><table><thead><tr><th>Campaña</th><th>Inicio / fin exclusivo</th><th>Estado</th><th>Verificación</th></tr></thead><tbody>{items.filter(x=>!month||String(x.data.starts_at).slice(0,7)<=month&&String(x.data.ends_at).slice(0,7)>=month).sort((a,b)=>Date.parse(String(a.data.starts_at))-Date.parse(String(b.data.starts_at))).map(x=><tr key={x.id}><td><a href={`/_emdash/admin/content/promotions/${x.id}`}>{String(x.data.title)}</a><small>{String(x.data.calendar_source??'Campaña propia')}</small></td><td>{format(x.data.starts_at)}<br/>{format(x.data.ends_at)}</td><td>{x.status==='draft'?'Borrador':x.status==='published'?'Publicada':x.status}</td><td>{x.data.offer_verified?'Confirmada':'Pendiente de confirmar'}<small>{String(x.data.verification_notes??'')}</small></td></tr>)}</tbody></table></div></div>;
}
export const pages={'/calendar':Calendar};
