import { useEffect, useState } from 'react';
import { DEFAULT_SETTINGS, type WhatsAppRule, type WhatsAppSettings } from './model';
type Choice = {id:string;label:string};
type Choices = {courses:Choice[];categories:Choice[];countries:Choice[]};
async function api<T>(path:string, body?:unknown):Promise<T> {
  const r=await fetch(`/_emdash/api/plugins/globos-whatsapp/${path}`,{method:body?'POST':'GET',credentials:'same-origin',headers:{'Content-Type':'application/json','X-EmDash-Request':'1'},...(body?{body:JSON.stringify(body)}:{})});
  const value=await r.json() as {success?:boolean;error?:{message?:string};data:T};
  if(!r.ok || !value.success) throw new Error(value.error?.message || 'No se pudo guardar la configuración.');
  return value.data as T;
}
const DAYS=['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];
const split=(text:string)=>text.split('\n').map(x=>x.trim()).filter(Boolean);
function Multiple({label,items,value,onChange}:{label:string;items:Choice[];value:string[];onChange:(v:string[])=>void}) {
  return <label>{label}<select multiple size={5} value={value} onChange={e=>onChange(Array.from(e.target.selectedOptions,o=>o.value))}>{items.map(i=><option key={i.id} value={i.id}>{i.label}</option>)}</select><small>Vacío: todos. Ctrl/Cmd para seleccionar varios.</small></label>;
}
function WhatsAppAdmin() {
  const [config,setConfig]=useState<WhatsAppSettings>(DEFAULT_SETTINGS);
  const [choices,setChoices]=useState<Choices>({courses:[],categories:[],countries:[]});
  const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  useEffect(()=>{Promise.all([api<{config:WhatsAppSettings}>('config'),api<Choices>('choices')]).then(([v,c])=>{setConfig(v.config);setChoices(c);setReady(true)}).catch(e=>setMessage(e.message));},[]);
  const update=<K extends keyof WhatsAppSettings>(key:K,value:WhatsAppSettings[K])=>setConfig(s=>({...s,[key]:value}));
  const ruleUpdate=(id:string,patch:Partial<WhatsAppRule>)=>update('rules',config.rules.map(r=>r.id===id?{...r,...patch}:r));
  const save=async()=>{setBusy(true);setMessage('');try{const v=await api<{config:WhatsAppSettings}>('save',config);setConfig(v.config);setMessage('Configuración guardada. Se aplica al abrir o recargar las páginas.')}catch(e){setMessage(e instanceof Error?e.message:'Error al guardar.')}finally{setBusy(false)}};
  return <div className="globos-wa-admin"><style>{`.globos-wa-admin{max-width:1100px;padding:24px;color:var(--foreground,inherit)}.globos-wa-admin h1{font-size:28px;font-weight:700}.globos-wa-admin h2{font-size:20px;font-weight:650;margin-bottom:14px}.globos-wa-admin section,.globos-wa-admin details{border:1px solid #8885;border-radius:10px;padding:20px;margin:20px 0}.globos-wa-admin label{display:flex;flex-direction:column;gap:6px;font-size:14px}.globos-wa-admin input:not([type=checkbox]),.globos-wa-admin select,.globos-wa-admin textarea{width:100%;border:1px solid #8888;border-radius:6px;padding:9px;background:var(--background,transparent);color:inherit}.globos-wa-admin textarea{min-height:90px}.globos-wa-admin .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:18px}.globos-wa-admin .check{display:flex;flex-direction:row;align-items:center;gap:8px}.globos-wa-admin small{opacity:.7}.globos-wa-admin button{padding:9px 15px;background:#1666d8;color:white;border-radius:6px;margin:10px 8px 0 0}.globos-wa-admin button:disabled{opacity:.5}.globos-wa-admin summary{cursor:pointer;font-weight:600}.globos-wa-admin [role=status]{padding:12px;border:1px solid #8888;border-radius:6px}.globos-wa-admin .danger{background:#ba253b}.globos-wa-admin .checks{display:flex;gap:16px;flex-wrap:wrap;margin:16px 0}`}</style>
    <h1>WhatsApp de Curso de Globos</h1><p>Botón contextual por curso, categoría y país. Funciona con cualquier plantilla que incluya los hooks de EmDash.</p>
    {message&&<p role="status">{message}</p>}{!ready?<p>Cargando configuración…</p>:<>
    <section><h2>Configuración general</h2><div className="checks">{([['enabled','Mostrar WhatsApp'],['mobile','Mostrar en móvil'],['desktop','Mostrar en escritorio'],['animate','Animación suave']] as const).map(([key,label])=><label key={key} className="check"><input type="checkbox" checked={config[key]} onChange={e=>update(key,e.target.checked)}/>{label}</label>)}</div>
    <div className="grid"><label>Número internacional<input value={config.number} placeholder="Vacío: número del país" onChange={e=>update('number',e.target.value)}/><small>Incluye código de país. Sin espacios ni el signo +.</small></label><label>Etiqueta accesible<input value={config.label} onChange={e=>update('label',e.target.value)}/></label><label>Lado<select value={config.position} onChange={e=>update('position',e.target.value as 'left'|'right')}><option value="right">Derecha</option><option value="left">Izquierda</option></select></label><label>Color<input type="color" value={config.color} onChange={e=>update('color',e.target.value)}/></label>{([['x','Separación horizontal (px)',300],['y','Separación inferior (px)',500],['delay','Espera antes de aparecer (segundos)',120]] as const).map(([key,label,max])=><label key={key}>{label}<input type="number" min="0" max={max} value={config[key]} onChange={e=>update(key,Number(e.target.value))}/></label>)}</div>
    <label>Mensaje predeterminado<textarea value={config.message} onChange={e=>update('message',e.target.value)}/><small>Variables: {'{titulo}, {curso}, {categoria}, {pais}, {url}'}. El enlace no incluye parámetros personales de la URL.</small></label>
    <label>Ocultar en estas rutas<textarea value={config.hiddenPaths.join('\n')} onChange={e=>update('hiddenPaths',split(e.target.value))}/><small>Una por línea. Ejemplo: /legal/* o /co/curso-de-barberia/.</small></label></section>
    <section><h2>Horario de atención</h2><p>Fuera del horario el botón se oculta. Con ambas horas vacías está disponible todo el día.</p><div className="grid"><label>Zona horaria<input value={config.timezone} placeholder="America/Bogota" onChange={e=>update('timezone',e.target.value)}/></label><label>Desde<input type="time" value={config.startTime} onChange={e=>update('startTime',e.target.value)}/></label><label>Hasta<input type="time" value={config.endTime} onChange={e=>update('endTime',e.target.value)}/></label></div><div className="checks">{DAYS.map((day,i)=><label className="check" key={day}><input type="checkbox" checked={config.weekdays.includes(i)} onChange={e=>update('weekdays',e.target.checked?[...config.weekdays,i]:config.weekdays.filter(d=>d!==i))}/>{day}</label>)}</div></section>
    <section><h2>Reglas de atención</h2><p>Las condiciones de una regla se combinan. Si coinciden varias, gana la mayor prioridad. Las exclusiones y el horario generales siempre se respetan.</p>
    {config.rules.map((r,i)=><details key={r.id}><summary>{i+1}. {r.label} · prioridad {r.priority}{!r.enabled?' · inactiva':''}</summary><div className="checks"><label className="check"><input type="checkbox" checked={r.enabled} onChange={e=>ruleUpdate(r.id,{enabled:e.target.checked})}/>Regla activa</label></div><div className="grid"><label>Nombre de la regla<input value={r.label} onChange={e=>ruleUpdate(r.id,{label:e.target.value})}/></label><label>Prioridad<input type="number" min="-1000" max="1000" value={r.priority} onChange={e=>ruleUpdate(r.id,{priority:Number(e.target.value)})}/></label><label>Número de este equipo<input value={r.number} placeholder="Vacío: heredar número general" onChange={e=>ruleUpdate(r.id,{number:e.target.value})}/></label><Multiple label="Cursos" items={choices.courses} value={r.courses} onChange={courses=>ruleUpdate(r.id,{courses})}/><Multiple label="Categorías" items={choices.categories} value={r.categories} onChange={categories=>ruleUpdate(r.id,{categories})}/><Multiple label="Países" items={choices.countries} value={r.countries} onChange={countries=>ruleUpdate(r.id,{countries})}/></div>
      <label>Mensaje específico<textarea value={r.message} placeholder="Vacío: mensaje general" onChange={e=>ruleUpdate(r.id,{message:e.target.value})}/></label><label>Limitar a estas rutas<textarea value={r.paths.join('\n')} onChange={e=>ruleUpdate(r.id,{paths:split(e.target.value)})}/></label><div className="grid">{(['startsAt','endsAt'] as const).map(key=><label key={key}>{key==='startsAt'?'Comienza (hora local de tu dispositivo)':'Termina (hora local de tu dispositivo)'}<input type="datetime-local" value={r[key]?new Date(Date.parse(r[key])-new Date(r[key]).getTimezoneOffset()*60000).toISOString().slice(0,16):''} onChange={e=>ruleUpdate(r.id,{[key]:e.target.value?new Date(e.target.value).toISOString():''})}/></label>)}</div><button className="danger" type="button" onClick={()=>update('rules',config.rules.filter(x=>x.id!==r.id))}>Quitar regla</button></details>)}
    <button type="button" onClick={()=>update('rules',[...config.rules,{id:crypto.randomUUID(),label:'Nueva regla',enabled:true,priority:100,courses:[],categories:[],countries:[],paths:[],number:'',message:'',startsAt:'',endsAt:''}])}>Añadir regla</button></section>
    <button disabled={busy} onClick={save}>{busy?'Guardando…':'Guardar WhatsApp'}</button></>}
  </div>;
}
export const pages = { '/whatsapp': WhatsAppAdmin };
